name: Test & Deploy
on:
  push:
    branches:
      - master
jobs:
  test_deploy:
    name: Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Python 3.8.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - name: Setup pipenv
        run: |
          sudo pip install pipenv --upgrade
          pipenv --python 3.8.6
          pipenv install -d
      - name: Test
        run: make test
      - name: Setup AWS CDK
        run: |
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt-get -y -qq install nodejs
          sudo npm i -g aws-cdk
      - name: Deploy
        run: |
          AWS_DEFAULT_REGION="us-east-1" \
          AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          SPOTIFY_USER_ID="${{ secrets.SPOTIFY_USER_ID }}" \
          JQBX_ROOM_ID="${{ secrets.JQBX_ROOM_ID }}" \
          JQBX_BOT_DISPLAY_NAME="${{ secrets.JQBX_BOT_DISPLAY_NAME }}" \
          JQBX_BOT_IMAGE_URL="${{ secrets.JQBX_BOT_IMAGE_URL }}" \
          cdk deploy --require-approval never --verbose